spring:
  #profiles 선언하여 적용할 profile을 선택 한다.
  profiles: 
    active: release 
  
  #DB 설정
  datasource:
    url: jdbc:log4jdbc:postgresql://192.168.0.200:5432/jhit_db
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: jhit_app
    password: jhit1128!
    
  #Hikari 설정
  hikari:  
    maximum-pool-size: 10 
    #connection-test-query: SELECT 1 
    data-source-properties: 
      cachePrepStmts: true 
      prepStmtCacheSize: 250 
      prepStmtCacheSqlLimit: 2048 
      useServerPrepStmts: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    static-path-pattern: /resources/**
  
  #JSP 바로적용 설정
  devtools:
    livereload:
      enabled: true

#내장 서버 포트
server.port: 8080

# 오류 페이지 설정
server: 
  error: 
    whitelabel: 
      enabled: false

#log4jdbc 설정
log4jdbc: 
  spylogdelegator: 
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator 
  dump: 
    sql: 
      maxlinelength: 0

--- #local 환경 
spring: 
  profiles: local 
logging: 
  level: 
    root: error
    com.jhit: debug

--- #release 환경 
spring: 
  profiles: release
logging: 
  level: 
    root: error
    com.jhit: debug
